### PR TITLE
Several fixes for #21 missing translations

### PR DESCRIPTION
**Pull request by Tdue21**
I have made some changes to the source, in order to fix some of the issues regarding translations. It is not an complete fix, there are some issues remained, regarding the default overlays as well as JavaFX internal dialogs. 
Other than that, I think most translation issues are fixed now.

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/tokentool/25)

### CODE REVIEW

**Comment by Tdue21** [comment]
Oh, I had to update the gradle used to 4.5.1 (same as MapTool in order to get the stuff to compile).

**Comment by Tdue21** [comment]
I do not know how to fix the Travis CI build. It seems to be something about the code format, but I do not know what.

**Comment by JamzTheMan** [comment]
Thanks! I'll take a look at this. I've been meaning to merge 2.1 in from my fork anyway and get the CI updated from everything we did in MapTool 1.5...

**Comment by Tdue21** [comment]
I've closed this PR, as I experienced some conflicts merging the new develop branch into my fork. I'll redo my changes and submit a new PR.

**Pull request closed without merging**
